requires 'Moose'                                                      , 0;
requires 'MooseX::Role::Parameterized'                                , 0;
requires 'REST::Consumer'                                             , 0;
requires 'Test::Exception'                                            , 0;
requires 'Timed::Logger';
requires 'Timed::Logger::Dancer::AdoptPlack';
requires 'Try::Tiny'                                                  , 0;
requires 'Test::Easy';
requires 'Test::MockObject';
requires 'WWW::Curl::UserAgent';
